// <auto-generated />
using System;
using BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackEnd.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20210419035358_updateDumpData")]
    partial class updateDumpData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BackEnd.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Hair"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Makeup"
                        },
                        new
                        {
                            ID = 3,
                            Name = "SkinCare"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Fragnance"
                        });
                });

            modelBuilder.Entity("BackEnd.Models.Product", b =>
                {
                    b.Property<int>("proID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("proDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("proName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("proPrice")
                        .HasColumnType("float");

                    b.HasKey("proID");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            proID = 1,
                            CategoryId = 1,
                            Image = "p1.webp",
                            proDescription = "Product Summary/Product Desscription",
                            proName = "Product Name 1",
                            proPrice = 50.0
                        },
                        new
                        {
                            proID = 2,
                            CategoryId = 1,
                            Image = "p3.webp",
                            proDescription = "Product Summary/Product Desscription",
                            proName = "Product Name 2",
                            proPrice = 50.0
                        },
                        new
                        {
                            proID = 3,
                            CategoryId = 1,
                            Image = "p4.webp",
                            proDescription = "Product Summary/Product Desscription",
                            proName = "Product Name 3",
                            proPrice = 50.0
                        },
                        new
                        {
                            proID = 17,
                            CategoryId = 1,
                            Image = "p5.webp",
                            proDescription = "Product Summary/Product Desscription",
                            proName = "Product Name 4",
                            proPrice = 50.0
                        },
                        new
                        {
                            proID = 18,
                            CategoryId = 1,
                            Image = "p1.webp",
                            proDescription = "Product Summary/Product Desscription",
                            proName = "Product Name 1",
                            proPrice = 50.0
                        },
                        new
                        {
                            proID = 19,
                            CategoryId = 1,
                            Image = "p3.webp",
                            proDescription = "Product Summary/Product Desscription",
                            proName = "Product Name 2",
                            proPrice = 50.0
                        },
                        new
                        {
                            proID = 20,
                            CategoryId = 1,
                            Image = "p4.webp",
                            proDescription = "Product Summary/Product Desscription",
                            proName = "Product Name 3",
                            proPrice = 50.0
                        },
                        new
                        {
                            proID = 21,
                            CategoryId = 1,
                            Image = "p5.webp",
                            proDescription = "Product Summary/Product Desscription",
                            proName = "Product Name 4",
                            proPrice = 50.0
                        },
                        new
                        {
                            proID = 22,
                            CategoryId = 1,
                            Image = "p1.webp",
                            proDescription = "Product Summary/Product Desscription",
                            proName = "Product Name 1",
                            proPrice = 50.0
                        },
                        new
                        {
                            proID = 23,
                            CategoryId = 1,
                            Image = "p3.webp",
                            proDescription = "Product Summary/Product Desscription",
                            proName = "Product Name 2",
                            proPrice = 50.0
                        },
                        new
                        {
                            proID = 24,
                            CategoryId = 1,
                            Image = "p4.webp",
                            proDescription = "Product Summary/Product Desscription",
                            proName = "Product Name 3",
                            proPrice = 50.0
                        },
                        new
                        {
                            proID = 25,
                            CategoryId = 1,
                            Image = "p5.webp",
                            proDescription = "Product Summary/Product Desscription",
                            proName = "Product Name 4",
                            proPrice = 50.0
                        },
                        new
                        {
                            proID = 5,
                            CategoryId = 2,
                            Image = "p1.webp",
                            proDescription = "Product Summary/Product Desscription",
                            proName = "Product Name 6",
                            proPrice = 50.0
                        },
                        new
                        {
                            proID = 6,
                            CategoryId = 2,
                            Image = "p3.webp",
                            proDescription = "Product Summary/Product Desscription",
                            proName = "Product Name 7",
                            proPrice = 50.0
                        },
                        new
                        {
                            proID = 7,
                            CategoryId = 2,
                            Image = "p4.webp",
                            proDescription = "Product Summary/Product Desscription",
                            proName = "Product Name 8",
                            proPrice = 50.0
                        },
                        new
                        {
                            proID = 8,
                            CategoryId = 2,
                            Image = "p5.webp",
                            proDescription = "Product Summary/Product Desscription",
                            proName = "Product Name 9",
                            proPrice = 50.0
                        },
                        new
                        {
                            proID = 9,
                            CategoryId = 3,
                            Image = "p1.webp",
                            proDescription = "Product Summary/Product Desscription",
                            proName = "Product Name 10",
                            proPrice = 50.0
                        },
                        new
                        {
                            proID = 10,
                            CategoryId = 3,
                            Image = "p3.webp",
                            proDescription = "Product Summary/Product Desscription",
                            proName = "Product Name 11",
                            proPrice = 50.0
                        },
                        new
                        {
                            proID = 11,
                            CategoryId = 3,
                            Image = "p4.webp",
                            proDescription = "Product Summary/Product Desscription",
                            proName = "Product Name 12",
                            proPrice = 50.0
                        },
                        new
                        {
                            proID = 12,
                            CategoryId = 3,
                            Image = "p5.webp",
                            proDescription = "Product Summary/Product Desscription",
                            proName = "Product Name 13",
                            proPrice = 50.0
                        },
                        new
                        {
                            proID = 13,
                            CategoryId = 4,
                            Image = "p1.webp",
                            proDescription = "Product Summary/Product Desscription",
                            proName = "Product Name 14",
                            proPrice = 50.0
                        },
                        new
                        {
                            proID = 14,
                            CategoryId = 4,
                            Image = "p3.webp",
                            proDescription = "Product Summary/Product Desscription",
                            proName = "Product Name 15",
                            proPrice = 50.0
                        },
                        new
                        {
                            proID = 15,
                            CategoryId = 4,
                            Image = "p4.webp",
                            proDescription = "Product Summary/Product Desscription",
                            proName = "Product Name 16",
                            proPrice = 50.0
                        },
                        new
                        {
                            proID = 16,
                            CategoryId = 4,
                            Image = "p5.webp",
                            proDescription = "Product Summary/Product Desscription",
                            proName = "Product Name 17",
                            proPrice = 50.0
                        });
                });

            modelBuilder.Entity("BackEnd.Models.Rating", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<string>("UserAcc")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.HasIndex("UserAcc");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("BackEnd.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("BackEnd.Models.Product", b =>
                {
                    b.HasOne("BackEnd.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BackEnd.Models.Rating", b =>
                {
                    b.HasOne("BackEnd.Models.Product", "Product")
                        .WithMany("Ratings")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserAcc");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BackEnd.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BackEnd.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BackEnd.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackEnd.Models.Product", b =>
                {
                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
